// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrI11YNhEpCd-B5JMvrkCrXG5VVAol6Fo',
    appId: '1:131083712954:web:46f21a09ff0cbff4fd4583',
    messagingSenderId: '131083712954',
    projectId: 'newsocial-6dcbf',
    authDomain: 'newsocial-6dcbf.firebaseapp.com',
    storageBucket: 'newsocial-6dcbf.appspot.com',
    measurementId: 'G-R4VSGBJY2C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDd5dtD6RnIH5M7klhi4kdSS33he4I667M',
    appId: '1:131083712954:android:03516b636f76f7b8fd4583',
    messagingSenderId: '131083712954',
    projectId: 'newsocial-6dcbf',
    storageBucket: 'newsocial-6dcbf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcJRHBM-X47HvaSv2H5Mf0ykxhEh9HpMI',
    appId: '1:131083712954:ios:c9d22368204cfd41fd4583',
    messagingSenderId: '131083712954',
    projectId: 'newsocial-6dcbf',
    storageBucket: 'newsocial-6dcbf.appspot.com',
    iosBundleId: 'com.example.food',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcJRHBM-X47HvaSv2H5Mf0ykxhEh9HpMI',
    appId: '1:131083712954:ios:c9d22368204cfd41fd4583',
    messagingSenderId: '131083712954',
    projectId: 'newsocial-6dcbf',
    storageBucket: 'newsocial-6dcbf.appspot.com',
    iosBundleId: 'com.example.food',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCrI11YNhEpCd-B5JMvrkCrXG5VVAol6Fo',
    appId: '1:131083712954:web:b08aa15bf9899d8efd4583',
    messagingSenderId: '131083712954',
    projectId: 'newsocial-6dcbf',
    authDomain: 'newsocial-6dcbf.firebaseapp.com',
    storageBucket: 'newsocial-6dcbf.appspot.com',
    measurementId: 'G-WX1KPFL56F',
  );
}
